### ISSUE TITLE
Gui tests: replace fixed waits with smart waits

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#139]
We can wait till the expected UI element appears, instead of using fixed waits.

**Comment by chao1995** [comment]
@damithc Hi Prof, while I was investigating this issue, I found there are a couple of waits are just to help tester know what's going on, for example this one
```java
protected void setTextField(String textFieldId, String newText) {
        guiRobot.clickOn(textFieldId);
        ((TextField) guiRobot.lookup(textFieldId).tryQuery().get()).setText(newText);

        guiRobot.sleep(500); // so that the texts stays visible on the GUI for a short period
}
```

The tests will still pass if we remove `guiRobot.sleep(500)` because whether or not the texts stay visible for a while is not relevant to the tests. But without it, the tester wound not know what command is executed.

So should we remove such waits or keep them?

Thanks for the help!

**Comment by damithc** [comment]
Yes @chao1995, those waits should be kept.
We tried `guiRobot.write()` before. It takes way too long :-)

**Comment by chao1995** [comment]
@damithc Haha yeah I just experienced this problem.
