### ISSUE TITLE
Find a way to convert markdown documents to html and pdf

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#175]
Students might have to use more styling (colors etc.) in the docs and submit documents in pdf format. It would be good if we can find a way to do those two things with minimum effort.

### Option 1: Github Flavored Markdown
* Use default themes and GH pages to render to html
* Print to a PDF writer to convert to PDF

Pros:
* Easy to edit

Cons: 
* No extra stuff like TOC, admonition blocks etc.
* Default themes don't fit very well

### Option 2: AsciiDocs
* Use Github's support to render to basic
* Optional: Run script locally to generate fancy html
* Run script locally to generate PDF

Pros:
* Lots of bells and whistles (TOC, admonition, etc.)
* Proper pdf generation

Cons:
* Need to install python etc.
* Syntax highlighting is not as good as GFMD
* More complex syntax, less editor support

### Option 3: Strapdown
* Html files, but the body can contain markdown
* Render as html and print to a pdf writer

Pros:
* Can be combined with bootstrap
* Can preview locally without running a script

Cons:
* Slow to render
* **Can't seem to get it to work when served from GitHub :-p**

**Comment by pyokagan** [comment]
@damithc Is there a requirement that the markdown documents have to be viewable on Github (with their markdown renderer?) Github's markdown variant is quite [weak](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) e.g. no admonitions, no figure captions, no header numbering, no toc generation etc. We can't use HTML as well because Github aggressively [strips HTML](https://github.com/github/markup#github-markup) from the rendered output. If this limitation is lifted, we could use one of the millions (:-P) of markdown variants out there which have much better support for document markup that transitions seamlessly to html or pdf output, at the cost of the Githu's output being slightly undecipherable.

Another solution is to use a richer markup format like [asciidoc](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/) which [Github supports](https://github.com/opendevise/asciidoc-samples/blob/master/article.adoc). It supports admonitions, figure captions, header numbering, toc generation etc. :)

FWIW, for my group I used Github markdown + [pandoc](http://pandoc.org/) and a lot of filters, which is probably not "minimum effort" :-P (https://github.com/CS2103AUG2016-T11-C4/main/pull/71)

**Comment by damithc** [comment]
It would be nice if we can make use of GitHub markdown as much as we can (i.e. use GitHub rendering most of the time and generate pdf files only at release points). I'm open to ditching it altogether but only as a last resort.

One option is to provide the conversion infrastructure as part of the project setup (gradle tasks etc.)
Another option is to let students use html/css etc for additional formatting such as admonition blocks (this is a nice way for students to learn a bit of web technologies), and use github.io to render to html. In that case we'll have to provide the extra css files. Also, there should be an easy way to convert from html to pdf (just 'save as pdf' from the browser?)

**Comment by damithc** [comment]
Other possibly related resources:
* http://strapdownjs.com/
* http://rawgit.com/

Browsers cannot do 'save as pdf', but can print to a pdf writer. The resulting pdf file is decent (looks exactly same as the web page) but hyperlinks will not work.

**Comment by kychua** [comment]
How about something like this: (draft implemented [here](https://github.com/kychua/addressbook-level4))?

Use Asciidoc format for documentation with Asciidoctor gradle plugin that converts docs to html/pdf format. Travis pushes generated html files to gh-pages branch automatically for commits to master branch.

* docs are viewable on Github but some features are missing e.g. colours, example blocks are not displayed with the proper formatting (see [example](https://github.com/kychua/addressbook-level4/blob/master/docs/Documentation.adoc))
* [github pages](https://kychua.github.io/addressbook-level4) shows proper formatting
* generated [pdf](https://github.com/kychua/addressbook-level4/blob/9177a5bcdbe46eaaaeafab62f0a699126d69ec2c/Documentation.pdf) files do not support colours for words -> print to pdf using github pages instead?
* users can use their own css stylesheets for customisation
* only change to setup procedure is having to generate personal access token on git and adding it to Travis

**Comment by damithc** [comment]
Sounds good @kychua 

> generated pdf files do not support colours for words -> print to pdf using github pages instead?

You mean using a pdf writer? Doesn't that destroy hyper links? Is there a better way?

How about local preview? Any eclipse plugin? I guess user can run the gradle command to generate the files and view them too.

**Comment by kychua** [comment]
Using Chrome's 'save as pdf' seems to preserve hyperlinks. Actually, realised that if html is used to set colors of individual words, colors of individual words are displayed properly in the pdf. Other formatting e.g. strikethrough don't seem to work though. I'm still trying to find another way; formatting seems to be worse when using other tools. 

Eclipse has Mylyn WikiText plugin that has very basic support (basic formatting (italic, bold etc.), headings, lists) for asciidoc. I usually check the generated files.

**Comment by damithc** [comment]
> Using Chrome's 'save as pdf' seems to preserve hyperlinks.

Indeed it does. We should document it in the dev guide as the steps are not obvious. 

Any further progress on this? We need to finish this by week 4.

**Comment by kychua** [comment]
Still ongoing, PR here: https://github.com/se-edu/addressbook-level4/pull/268

**Comment by kychua** [comment]
Split into 3 issues:
1. Add asciidoctor to Gradle #269
2. Set up workflow for asciidocs #270 
3. Migrate documentation from markdown to asciidoc #271

**Comment by pyokagan** [comment]
Resolved by https://github.com/se-edu/addressbook-level4/pull/452
