### ISSUE TITLE
Explore possibility of adopting reviewable.io for code reviews.

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#240]
As per title

**Comment by pyokagan** [comment]
Eh my current position is that I think we should just drop it and find another code review tool or invent our own lightweight tooling. Maybe it's just because I'm not familiar with the reviewable.io UI currently, but I'm finding it quite hard to use.

## The Good

* Ability to review commit by commit. It worked extremely well for #209 at first but with the v5 submitted all of the diffs are all over the place :-/

## The Bad

* Not GitHub, which may scare away contributors.

* Does not show commit messages.

(Will edit as I gain more experience. Hopefully it's just because I'm using it wrongly).

**Comment by damithc** [comment]
My vote is leaning towards 'drop' as well. 

# The Good
* There is a way to ensure every issue raised is resolved (Github seems to swallow/hide past comments when the code is updated)

# The Bad
* Seems it is not a mature product yet (e.g. documentation is just a FAQ only) and there's the risk of it disappearing altogether. 
* Could not find a way to tell it to 'show white space differences'
* Could not see line numbers

**Comment by damithc** [comment]
@pyokagan shall we drop the idea? I've stopped using reviewable.io since a few days ago.

**Comment by pyokagan** [comment]
@damithc Yeah let's drop it. I'll see if I can expand on the "PR summary" idea instead.

**Comment by damithc** [comment]
Conclusion:  Reviewable.io will not be adopted in its current state because the negatives outweigh the positives.

**Comment by pyokagan** [comment]
Yeah, I think as long as an external service *forces all* contributors and reviewers to use a different service that's not GitHub, it can't really be used.

Instead, we could probably go for a approach where we provide some additional tooling, and contributors/reviewers can use them if they want to improve their workflow (optional tooling).

The "pr summary" tool is a good example, because it doesn't require that all PRs use it. The only thing missing is that it does not provide interdiffs, so I'll look into fixing that.
