### ISSUE TITLE
HTML anchors in UserGuide.md DeveloperGuide.md all broken

### ISSUE THREAD

**Issue by sooyj** [se-edu/addressbook-level4#340]
The HTML anchors in both documents are incorrectly generated. The anchor in the index (the content list at the top of the document) e.g. https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.md**#design**  does not match the actual anchor:
https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.md**#2-design**

**Comment by acjh** [comment]
A fix was tried and reverted. Please see @damithc's comments in #246.

**Comment by damithc** [comment]
Actually, we should give this issue another try. Previously the links worked in Github Pages version but not in the markdown version; but now they don't work in either version. It's possible that Github fixed the bug in link generation since the last time we tried it.

**Comment by acjh** [comment]
Oh yes, they did :)

**Comment by yamgent** [comment]
If GitHub fixed it, we can consider inviting the author of #318 to re-open his PR and continue his work (but if it is deemed urgent, then we can also consider recommitting 1054d0d13f0d39a627db5bd53882bb4bdd162289 immediately instead).

**Comment by damithc** [comment]
I think it is not terribly urgent. CS2103 students can fix it themselves. In any case, they are unlikely to be able to pull from our repo because their repo must be quite different from ours by now. Once we fix it in the our repo, we can send a link to that PR to CS2103 students for them to manually copy the fix. Yes, let's see if the author of the previous PR is interested to continue.
