### ISSUE TITLE
update SampleDataUtil and TestUtil

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#384]
`TestUtil#getSamplePersonData` should be using `PersonBuilder` to create the `Person` objects instead.

Same goes for `SampleDataUtil#getSamplePersons`. The only concern for `SampleDataUtil` using `PersonBuilder` is that `PersonBuilder` is used only in testing and should not be used in the main application.

Then, `SampleDataUtil#getTagSet` can be placed as a private helper method inside `PersonBuilder` instead.

**Comment by Zhiyuan-Amos** [comment]
@yamgent need your thoughts; when you're free :)

**Comment by yamgent** [comment]
The necessity of `PersonBuilder` will depend on whether we have too many constructors for the `Person` class (the builder pattern is to avoid the [telescoping constructor antipattern](http://www.captaindebug.com/2011/05/telescoping-constructor-antipattern.html#.WQf7JdqGOUk)).

For our implementation, all except one of our `Person` field are mandatory, as such, I don't think it is necessary to use the `PersonBuilder` class for our `SampleDataUtil` if we are expected to fill in all of the fields properly.

The reason why `PersonBuilder` existed is to mainly help us avoid having to fill up all fields for some test cases, by making those fields having a default value instead, if those fields are not important for that test. If we are filling up all of the fields on our own anyway, we can just utilise the `Person` constructor instead of `PersonBuilder`.

**Comment by Zhiyuan-Amos** [comment]
@yamgent Cool noted, thanks much for your guidance :)
