### ISSUE TITLE
Create a new Index class

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#438]
The codebase uses a mixture of one-based index and zero-based index, due to the difference in the GUI (one-based) and programming semantics (zero-based).

The conversion between the two indices are done in different location for different commands, making its usage inconsistent.

Let's create a new Index class, which allow us to avoid having to deal with the index type in the first place.

Also the conversion should only be done at the boundary of the component.

![index](https://cloud.githubusercontent.com/assets/3168908/26533573/49926e36-444d-11e7-8d40-3ff7da2cc71e.png)

**Comment by pyokagan** [comment]
Very nice 👍 

I don't think we need the interfaces though?

**Comment by yamgent** [comment]
@pyokagan 

> I don't think we need the interfaces though?

The interface is to allow certain methods to "declare" that they are only using a certain type of index (for example, the `Model` will never have a reason to use `OneBasedIndex`, so its methods will only take in `ZeroBasedIndex`).

**Comment by pyokagan** [comment]
@yamgent 
> The interface is to allow certain methods to "declare" that they are only using a certain type of index

The purpose of the `Index` class is to make it so that callers would not need to care about whether a method uses one-based or zero-based indexes internally, right?

So, there's no point to methods exposing whether they use zero-based or one-based indexes internally through the `ZeroBasedIndex` or `OneBasedIndex` interfaces? (YAGNI?)

To put it another way, is there a use case where a class will *only* implement `OneBasedIndex` or `ZeroBasedIndex`?

**Comment by pyokagan** [comment]
> To put it another way, is there a use case where a class will only implement OneBasedIndex or ZeroBasedIndex?

If such classes were implemented, then it is no different from the current status quo, where indices have to be explicitly converted between one-based and zero-based indices, no?

> Furthermore, it prevents the model's code from using the OneBasedIndex version.

Rather than making model code call `getZeroBasedIndex()` throughout the code (which adds verbosity), just call `getZeroBasedIndex()` once at the component boundary?

e.g. given
```java
public void updatePerson(int filteredPersonListIndex, ReadOnlyPerson editedPerson)
```
add an overload
```java
public void updatePerson(Index filteredPersonListIndex, ReadOnlyPerson editedPerson) {
    updatePerson(filteredPersonListIndex.getZeroBasedIndex(), editedPerson);
}
```

**Comment by pyokagan** [comment]
> So, there's no point to methods exposing whether they use zero-based or one-based indexes internally through the ZeroBasedIndex or OneBasedIndex interfaces? (YAGNI?)

Trying to rephrase again :-P

I think it is a good idea for the `Index` class to be an abstraction which hides the details of whether a method uses zero-based indices internally or not. Having separate `ZeroBasedIndex` or `OneBasedIndex` interfaces is exposing those details and defeating the purpose of this abstraction in the first place.

**Comment by yamgent** [comment]
Discussed with Zhiyuan about this, your suggestion makes a lot of sense, will fix it in my upcoming PR.

**Comment by pyokagan** [comment]
Marking as `p.Medium`. I think this is worth doing and should be in the "final" addressbook-level4 product, especially since it seems to make writing tests much easier.
