### ISSUE TITLE
Dev guide: fix typos in the use case

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#608]
Current:
![image](https://user-images.githubusercontent.com/1673303/28870117-b03cb26c-77b1-11e7-8f30-ef113c2f6808.png)

Suggested:
`Use case ends` should be in the next line.

Use proper hierarchical listed instead of block quote formatting for nested levels.

**Comment by Zhiyuan-Amos** [comment]
![image](https://user-images.githubusercontent.com/19281514/29996337-8dd2efd4-902f-11e7-8a6a-658c35b69824.png)

Asciidoc doesn't recognise `2a.` and `3a.` as numbered points. If you notice carefully, there's a slight formatting different between the other numbered points such as `1.`, `2.` compared to them.

As such, there's no way to properly format the `3a1.` as a nested point, because `3a.` already isn't being recognised as a nested point. The current way of workaround looks ugly though, and cannot be extended to support another level of nesting i.e. the method doesn't work for `3a1a.`.
