### ISSUE TITLE
ModelManager: Should not post AddressBookChangedEvent

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#647]
`ModelManager` posts `AddressBookChangedEvent` whenever it updates the
`AddressBook`. For example, `ModelManager#deletePerson(ReadOnlyPerson)`
deletes the `ReadOnlyPerson` from the `AddressBook` and posts
`AddressBookChangedEvent`.

Posting of `AddressBookChangedEvent` should not be the job of 
`ModelManager` as it violates SRP; the `AddressBook` should be posting the
event to inform other components whenever it is updated.

Let's teach `AddressBook` to post this event instead.

**Comment by Zhiyuan-Amos** [comment]
@yamgent issue validation tq ^^

**Comment by damithc** [comment]
Some background: AddressBook is meant to be just a data container. It should not know about Events at all because Events are a concept that is part of the higher-level application workflow. The `Manager` title of the ModelManager is meant to imply that it is the object in charge of managing this higher level workflow on behalf of the Model so that the Model can remain simpler and reusable.

**Comment by Zhiyuan-Amos** [comment]
> Events are a concept that is part of the higher-level application workflow.

Ah yes I agree. Ok! Will close this issue.
