### ISSUE TITLE
JUnit: Update to use latest version

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#707]
We are currently using JUnit version 4.12. We can upgrade it to JUnit 5.0.0.

**Comment by Rinder5** [comment]
This will require major updates as there is no @rule annotation in JUnit 5, which we use quite often currently.

**Comment by Zhiyuan-Amos** [comment]
@Rinder5 possible to add some of the links so that those who wanna spend time on this issue can go read up on the resources? ^^

**Comment by Rinder5** [comment]
We have 2 rules used often:
- TemporaryFolder : Requires making a new TemporaryFolder class. Alternatively, JUnit5 may be working on an extension to make it easier to migrate from JUnit4 (see: https://github.com/junit-team/junit5/issues/1247)
- ExpectedException : Can be handled by JUnit5 by using org.junit.jupiter.migrationsupport.rules.ExpectedExceptionSupport, with minimal additions

**Comment by Zhiyuan-Amos** [comment]
Looks good! 👍

**Comment by Rinder5** [comment]
Gradle is planning on integrating JUnit5 support with version 4.6. Right now the solution I am working on uses the JUnit Platform plugin, which acts a bit differently than what we have now. Do you think we should put this on hold?
https://github.com/gradle/gradle/issues/828#issuecomment-351431932

**Comment by Zhiyuan-Amos** [comment]
Yup sounds good, great work on finding out this information ^^ One concern I have is that Gradle 4.6 may not be released that soon since 4.5.1 is only released 2 days ago. Are the many changes that are required to be made between our current Gradle version and version 4.6?

**Comment by damithc** [comment]
If the benefit of upgrading to JUnit5 is not high, we can afford to wait until gradle catch up.

**Comment by Rinder5** [comment]
At the moment, JUnit5 tests aren't captured within the normal tests run by Gradle. If we want to run JUnit5 tests, we need to import their plugin, which runs things differently than what we have running now.

More specifically, the test data isn't captured in Gradle's generated test file, and there is no easy option I can find for running code before each test (currently we use this to label tests for our CI for debugging).

Personally, I don't think there is a rush in upgrading, since the only other mentioned issue #786 can be done in JUnit4 also, albeit with a bit more hassle.
