### ISSUE TITLE
Clearing the contacts list does not clear the browser

### ISSUE THREAD

**Issue by tshradheya** [se-edu/addressbook-level4#731]
On doing the following commands in the mentioned order

* `select 1`
* `clear`

Even though the address book is cleared the browser still shows about the web page of 1st contact.

How I thought of fixing the bug: 
 
Every time on clearing the contacts list, call a function `model.resetBrowswrPanel()` which will raise an event handled in BrowserPanel and invoke the `loadDefaultWebpage()`

**Comment by pyokagan** [comment]
I personally would like the browser panel to be replaced with something more useful. Like a person details panel that provides more info about the person. As it stands the browser panel doesn't have much use.

**Comment by damithc** [comment]
> I personally would like the browser panel to be replaced with something more useful. Like a person details panel that provides more info about the person. As it stands the browser panel doesn't have much use.

Yes, it would be good to have a regular person details panel, as an example of how to use a bunch of regular UI controls. 

I don't mind removing browser panel but nice to have an example of loading a regular web page as well so that students can do a light-weight integration with an existing service such as Google Maps (May be help window is good enough for that?). Another option is to keep the browser panel but squeeze in a person info panel in the middle.

**Comment by yamgent** [comment]
@tshradheya, as mentioned in https://github.com/se-edu/addressbook-level4/pull/801#issuecomment-358942018, since this is your first time contributing to our repository, you might want to consider tackling an issue with a `d.FirstTimers` label first. :)
