### ISSUE TITLE
Issue with undo/redo and modifications to filtered lists

### ISSUE THREAD

**Issue by archthegit** [se-edu/addressbook-level4#737]
The following code sequence:
Find "Al"
Delete 1
List
Undo
Redo

deletes the wrong person after it is in the full unfiltered list. Can this be considered a bug?

**Comment by erik0704** [comment]
This also effects command like `edit`. Reproducing:

- `find David`

- `edit 1 n/David LiBug`  .Here person at index 4 got his name changed.

- `undo`. Full contact list displayed again. Person at index 4 got his name changed back to David Li

- `redo`. Person at index 1 now got their name change to David LiBug.

It seems to be that the `redo` command just execute the exact command entered disregard the current model state of the address book ?

**Comment by eldonng** [comment]
I am having the same issue with my own app. 
Also ran on the default AB4, and it has the same issue too.
I did these steps:
`find david irfan`
`delete 2`
`undo`
`redo`
Result: Bernice Yu gets deleted instead of Irfan Ibrahim.

I have attached the following images that are from AB4:
![img1](https://user-images.githubusercontent.com/30952400/32992592-85c3ccec-cd87-11e7-9875-8a02ee308af0.PNG)
![img2](https://user-images.githubusercontent.com/30952400/32992593-89c93ad4-cd87-11e7-9370-6f5b097bed92.PNG)
![img3](https://user-images.githubusercontent.com/30952400/32992595-8cc72890-cd87-11e7-90df-57f71e173c6c.PNG)
![img4](https://user-images.githubusercontent.com/30952400/32992597-8f9b0514-cd87-11e7-9b55-1901e72b1299.PNG)

**Comment by pyokagan** [comment]
Thanks all, I managed to reproduce this and it does seem like a bug.

I guess an easy fix would be to save the model filter state when executing an UndoableCommand, and restore the model filter before redoing that command. Though, the UI doesn't have a "current filter" indicator so that may disorient the user. Still probably the most doable solution though.

Thoughts? PRs welcome as well :-)

cc @Zhiyuan-Amos

**Comment by khooroko** [comment]
https://github.com/CS2103AUG2017-T17-B1/main/pull/296 you can refer to the command-related files in this PR.
Basically, instead of storing the index for each undoable command, the person to apply the command on is stored instead. This will guarantee that redoing will execute on the right person no matter which list is displayed.
To retrieve the person to apply the command to within the constructor cannot be done with the model implementation Address Book level 4. Our team created a ListObserver class that follows the singleton design and is initialised with the model in MainApp, so its static methods can be called in the command constructors to retrieve whatever information is needed of the current list.

**Comment by damithc** [comment]
Let's fix this before the next batch starts with AB4
