### ISSUE TITLE
Add different levels of comparison to equality methods of Person class

### ISSUE THREAD

**Issue by Lenaldnwj** [se-edu/addressbook-level4#742]
Not sure if this is intended or not.
The address book does not show the duplicate person error and allows us to add duplicates (readding the same person) as long as we change any of their other attributes when adding them.
![duplicates](https://user-images.githubusercontent.com/28468315/33016311-093b1dea-ce29-11e7-9dd8-9ca15d67d97a.png)

For instance,
add n/Johnny Eco Ela Doe Li p/98765437 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney

followed by,
add n/Johnny Eco Ela Doe Li p/98765433 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney

**Comment by pyokagan** [comment]
Yes, this is by design with the current implementation.

Still, it has been agreed in the past that it would be a good thing to have different levels of comparison for persons (see https://github.com/se-edu/addressbook-level2/issues/122), just that the code has not been ported to addressbook-level4 yet.
