### ISSUE TITLE
Use java.nio.file for file/path handling

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#750]
Constructing paths using string operations is error prone, but there's lots of areas in the code base where this is done, which sets a bad example.

Lots of APIs in the code base also take in Strings as file paths, which further encourages this kind of code.

**Comment by vivekscl** [comment]
I'll start work on this!

**Comment by vivekscl** [comment]
```java
     * <li> If the {@code name} begins with a {@code '/'}
     * (<code>'&#92;u002f'</code>), then the absolute name of the resource is the
     * portion of the {@code name} following the {@code '/'}.
     *
     * <li> Otherwise, the absolute name is of the following form:
     *
     * <blockquote>
     *   {@code modified_package_name/name}
     * </blockquote>
```

It seems like `Class#getResource` takes in string paths that only use `/` as a file separator. As a result,  this results in the UI tests to fail as `\` is being used for the file separator instead. This is because using `java.nio.file.Path` to handle file paths results in the conversion of the file separator based on the current operating system. Since `Class#getResource` only deems file paths that use `/` as valid, these tests would fail in a Windows computer as `Class#getResource` returns null. So in this case, is it better to leave the file path handling in the UI component to be just string concatenation?

**Comment by pyokagan** [comment]
@vivekscl 
> So in this case, is it better to leave the file path handling in the UI component to be just string concatenation?

Yeah you can leave it.
