### ISSUE TITLE
Remove 1.x tags from the repo

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#769]
Students are supposed to release 1.0 to 1.5 but some of those tags already exist in the repo. Any chance we can remove them before the next semester starts?

**Comment by pyokagan** [comment]
Done.

Note that downstream repos will still have the tags, so you will need to delete them (since I don't have write access to those repos). Alternatively, just re-fork the repo.

Also, the tags won't be deleted from developer's cloned copies of the repos, so just be careful not to push those deleted tags back and resurrect them :-P

**Comment by damithc** [comment]
Thanks @pyokagan. Reforked next sem repo.
