### ISSUE TITLE
Performance regression when the model filter is modified

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#796]
Bisected to 75cbfa3804ff365646e903514282d9313da4300e 

Reproduction:

1. Create 9999 persons in the address book
2. Launch AB-4, which will show the unfiltered list by default.
3. Run: find X, where X is the exact name of a person, such that the list only displays 1 person.
4. AB-4 takes a long time to run the command, and the UI completely freezes for around 25s which is way above a usable response time. Prior to the aforementioned commit it is fast enough.

A few guesses:

1. EasyBind.map is not implemented in a performant way, or
2. 75cbfa3804ff365646e903514282d9313da4300e has the effect of creating 9999 scene nodes inside the list box. JavaFX does not perform well with huge scene graphs, especially when lots of scene nodes are removed at once.

Quick script to generate a 9999 person addressbook:
```python
print('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>')
print('<addressbook>')
for i in range(9999):
    print('<persons>')
    print('<name>{}</name>'.format(''.join('ABCDEFGHIJ'[int(x)] for x in str(i))))
    print('<phone>123</phone>')
    print('<email>a@a</email>')
    print('<address>a</address>')
    print('</persons>')
print('</addressbook>')
```

**Comment by Zhiyuan-Amos** [comment]
Will take a look at it soon, since https://github.com/se-edu/addressbook-level4/commit/75cbfa3804ff365646e903514282d9313da4300e is done by me ><

**Comment by Zhiyuan-Amos** [comment]
> EasyBind.map is not implemented in a performant way

This implementation lags when executing `FindCommand`, but doesn't lag when executing `ListCommand`. I tried another [implementation](https://bugs.openjdk.java.net/browse/JDK-8091967?focusedCommentId=13795614&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13795614), and this implementation lags when starting the app and when executing `ListCommand`, but doesn't lag when executing `FindCommand`. I guess both implementations have their trade-offs. Can't seem to find other implementations where both "adding" and "removing" execute very quickly. This is related to the next point since creating `PersonCard`s take up a long time.

> 75cbfa3 has the effect of creating 9999 scene nodes inside the list box. JavaFX does not perform well with huge scene graphs

From [javadoc for Cell](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Cell.html):
`Because TreeView, ListView, TableView and other such controls can potentially be used for displaying incredibly large amounts of data, it is not feasible to create an actual Cell for every single item in the control. We represent extremely large data sets using only very few Cells. Each Cell is "recycled", or reused. This is what we mean when we say that these controls are virtualized.`

As such, perhaps what this [line](https://github.com/se-edu/addressbook-level4/commit/75cbfa3804ff365646e903514282d9313da4300e#diff-c588cfbcc88255b5a6f7ed05786ea908L73) does is that each `PersonCard` is only created when required (when we scroll up and down). As such, when executing both `FindCommand` and `ListCommand`, very few `PersonCard`s are deleted and created.

**Comment by pyokagan** [comment]
> A possible solution is to simply revert it; I don't think there's any issue. I can't understand my commit message now -.-,

Maybe try reverting the commit and seeing if it reintroduces any problems?

**Comment by pyokagan** [comment]
> Maybe try reverting the commit and seeing if it reintroduces any problems?

As in, revert locally on your computer first :-P
