### ISSUE TITLE
Unable to open MainWindow.fxml on SceneBuilder

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#840]
Bisected to: f710fcd6290a6cd71c4172994180b75f7fbe839c.

According to @eugenepeh, students are taught in AddressBook-Level3 to use [SceneBuilder](https://se-edu.github.io/se-book/javaTools/javaFXBasic/) to work on their UI; it was not taught to them how to program the UI on the .fxml file itself.

As such, this may be a problem as students may take some time to learn how to modify the UI using the .fxml file.

**Comment by damithc** [comment]
What are our options?

**Comment by eugenepeh** [comment]
Perhaps adding a gui section in `DeveloperGuide` to teach students how to work on gui enhancement?

We might also have to make the SceneBuilder LO in `addressbook-level3` obsolete in that case because its no longer relevant to `addressbook-level4` development

**Comment by pyokagan** [comment]
@damithc For context, here is the error:

![untitled](https://user-images.githubusercontent.com/109479/37072387-1799124e-21fc-11e8-845a-f1a864ce31fc.png)

The problem is that Gluon Scene Builder opens the file, but does not know how to handle the `javafx.stage.Stage` root object.

Options are:

* Revert the commit, and the commits that depend on it. We will lose the ability to directly declare properties on the stage and scene in the FXML file, but we can now open it in Gluon scene builder.
* Give up on Gluon Scene Builder.
* Submit a PR/ open an issue to Gluon Scene Builder to implement support for the `javafx.stage.Stage` object

**Comment by damithc** [comment]
What do you recommend?
For example, we can tell this batch to edit the fxml file directly. In the meantime we can try to get Gluon guys to fix the problem by next semester.

**Comment by eugenepeh** [comment]
>For example, we can tell this batch to edit the fxml file directly. In the meantime we can try to get Gluon guys to fix the problem by next semester.

To make it easier for this batch perhaps I can inform them that they can create a dummy fxml using the old `MainWindow.fxml`? They can design the layout using old `MainWindow.fxml` with the SceneBuilder then copy the main layout chunk back into the original `MainWindow.fxml`


Specifically these chunk:

https://github.com/se-edu/addressbook-level4/blob/2f4405c75cd21111952565a9706a9793b475c41e/src/main/resources/view/MainWindow.fxml#L27-L64

**Comment by damithc** [comment]
> Yup, what @eugenepeh suggested seems good. The chunk above consists of the layout of the components in MainWindow. Since the code added in f710fcd simply "wraps" around the existing .fxml code, students can use the old MainWindow.fxml code, update the structure accordingly, then paste back into their master branch's MainWindow.fxml.

Is there any way for an fxml file to 'include' another, in which case we can extract out the said part as a separate fxml?

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh @damithc I have reverted the PR, the build passes on my side. I've opened a PR on [nus-cs2103-AY1719S2 fork](https://github.com/nus-cs2103-AY1718S2/addressbook-level4/pull/56), but I closed it as I'm not too sure whether I should be opening PRs there (since students are opening PRs there too).

**Comment by eugenepeh** [comment]
@Zhiyuan-Amos Its too late, they have already created their organisations during the recess week >_<

**Comment by pyokagan** [comment]
Here's a patched version of Scene Builder that handles `javafx.stage.Stage` and `javafx.scene.Scene`. Work in progress. (Note: it's only built for JRE8)

https://gist.github.com/pyokagan/1e7258a9ef4e881ca35b5f3cbcf861bf/raw/c4f2bbd0f32834b1f84fa0c13191a714e8e73623/scenebuilder-8.5.0-SNAPSHOT-all.jar

**Comment by pyokagan** [comment]
> Here's a patched version of Scene Builder that handles javafx.stage.Stage and javafx.scene.Scene. Work in progress. 

PR is at https://github.com/se-edu/scenebuilder/pull/2

Please help to test and report any bugs to the PR. Patches are even more welcome. (It's a good opportunity to work with a much more complex code base ;-) )

**Comment by pyokagan** [comment]
@damithc 
> What do you recommend?

`Stage` controls certain aspects of the UI (e.g. the window title, minWidth, minHeight, maxWidth, maxHeight, whether the window is resizable or not) which definitely falls into UI design, so I believe that Scene Builder is more at fault here for not allowing FXML files to contain those objects. The option which provides the most benefit would be to fix Scene Builder directly. (Since it benefits other developers outside the project like [this one](https://bitbucket.org/gluon-oss/scenebuilder/issues/134/tab-not-accepted-as-root-element-in-fxml))

**Comment by damithc** [comment]
Thanks very much for the patched jar @pyokagan Is there a permalink for it, or the link given above is still correct? @eugenepeh please keep students updated.

**Comment by eugenepeh** [comment]
> @eugenepeh please keep students updated.

Got it, thanks for the fix @pyokagan !

**Comment by pyokagan** [comment]
@damithc 
> Thanks very much for the patched jar @pyokagan Is there a permalink for it, or the link given above is still correct?

No, the latest version is at https://github.com/se-edu/scenebuilder/pull/2 ,  via the snapshots stored in the AppVeyor build. Someone could probably make a permalink out of the AppVeyor build.

**Comment by pyokagan** [comment]
Support for opening FXML files with Stage/Scene as root has been contributed upstream: https://github.com/gluonhq/scenebuilder/pull/178

Gluon has recently released a release candidate for ["Scene Builder for Java 11"](https://gluonhq.com/products/scene-builder/), and I've confirmed that it contains my fixes. (Not sure if the scene builders for JDK 10/8 have been updated as well)

So, this issue has, as long last, been fixed.
