### ISSUE TITLE
Unable to pass Travis(Bugs)

### ISSUE THREAD

**Issue by ongkc** [se-edu/addressbook-level4#846]
https://travis-ci.org/ongkc/addressbook-level4/builds/353184759?utm_source=github_status&utm_medium=notification

Received this error in the link above, and unable to resolve despite numerous attempts.

**Comment by Zhiyuan-Amos** [comment]
> ERROR:src/main/resources/docs/UserGuide.html:681: no newline at EOF.

You have an error. :p The above is from the Travis logs.

**Comment by damithc** [comment]
hmm... 🤔 why are we linting the html file? I remember something similar happened before, but cannot remember the solution.

**Comment by Zhiyuan-Amos** [comment]
We may need to configure the checkstyle file for that. Our current checkstyle file checks for all files by default because we didn't specify which files to check for:

![image](https://user-images.githubusercontent.com/19281514/37393957-933faf64-27ad-11e8-9387-82e70688ecb7.png)

To configure to only check for `.java` etc:

![image](https://user-images.githubusercontent.com/19281514/37393940-88294342-27ad-11e8-952b-9588f9c27169.png)

**Comment by Zhiyuan-Amos** [comment]
@ongkc I saw your repo, you need to press `enter` to create a newline, not type `\n` :P

**Comment by ongkc** [comment]
Hi,

I entered a newline and try whatever possible line breaks and it still does
not pass travis's test.

**Comment by pyokagan** [comment]
@ongkc Committing files that are generated with `gradle processResources` is not a supported use case. You should delete `UserGuide.html` from the repo.

**Comment by Zhiyuan-Amos** [comment]
> Committing files that are generated with gradle processResources is not a supported use case. You should delete UserGuide.html from the repo.

@ongkc yup, you should delete the file and update .gitignore to ignore tracking this file. `UserGuide.html` is generated with `gradle processResources` using `UserGuide.adoc`. So if you need to update the `.html` file, you should update the `.adoc` file instead.
