### ISSUE TITLE
Replace core.Version with Runtime.Version

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#872]
If `Runtime.Version` from the Java library already does what we need, then there's no need for us to implement our own `Version` class and having to write tests for it.

**Comment by yamgent** [comment]
> According to the article and documentation, Runtime.Version returns the version of Java runtime environment. However, our `Version` class seems to specify the version of addressbook-level4 release, please correct me if I am wrong.

You are correct. `Runtime.Version` is designed to only be used for specifying the Java runtime version. It is not designed with an intention to be used as a version specifier for general Java applications.

Our version numbers are _slightly_ different from Java's version numbers. However, even if we were to change our version format to match Java's, I generally frown upon just directly using `Runtime.Version`, because it will encourage students to abuse the API in ways that it is not supposed to be used.

Closing this issue...
