### ISSUE TITLE
.gitignore: remove config.json

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#926]
Can we remove `config.json` from the `.gitignore` file?

Reason: students need to add a `_reposense/config.json` for their forks.

**Comment by pyokagan** [comment]
I guess its meant to ignore the `config.json` file created and read by the application.

Rather than being removed, it should be made more specific (i.e. `/config.json` instead of `config.json`).

Same goes for many of the entries in the `.gitignore` file -- they are more general than they should be.

**Comment by eugenepeh** [comment]
hmm, why not just add a sample `_reposense/config.json` in AB?

**Comment by pyokagan** [comment]
@eugenepeh 

> hmm, why not just add a sample `_reposense/config.json` in AB?

That's a different issue from "the gitignore file is ignoring files that it did not intend to ignore".

**Comment by eugenepeh** [comment]
> That's a different issue from "the gitignore file is ignoring files that it did not intend to ignore".

Yes but it solves the reason

> Reason: students need to add a _reposense/config.json for their forks.

**Comment by pyokagan** [comment]
@eugenepeh 
> Yes but it solves the reason
> 
> > Reason: students need to add a _reposense/config.json for their forks.

It solves *this* use case, but it doesn't solve the *root* cause. In the future if someone wants to add another file called `config.json`, the same problem would occur again.

**Comment by eugenepeh** [comment]
> It solves this use case, but it doesn't solve the root cause. In the future if someone wants to add another file called config.json, the same problem would occur again.

I think it was there in the first place because addressbook will create a `config.json`? Hence to prevent the generated file from being added to the repository, I don't think we should remove it at all.

**Comment by pyokagan** [comment]
@eugenepeh 
> I think it was there in the first place because addressbook will create a `config.json`? Hence to prevent the generated file from being added to the repository, I don't think we should remove it at all.

Yes, I agree. That's why I [suggested](https://github.com/se-edu/addressbook-level4/issues/926#issuecomment-430683953) to change the pattern to `/config.json` instead so that only the `config.json` at the repo root will be ignored (which is the intention).

**Comment by eugenepeh** [comment]
> Yes, I agree. That's why I suggested to change the pattern to /config.json instead so that only the config.json at the repo root will be ignored (which is the intention).

My bad for missing the comment. However for the original reason, I think we should still provide a sample `_reposense/config.json` to the students because the sample we put up on RepoSense is for general users. We could probably save the students some readings by providing them the config with the fields they need to replace. This also helps to prevent some students who create the file `_reposense/config.json` instead of `config.json` in the `_reposense` folder during the semester.

**Comment by damithc** [comment]
We do provide customized config file templates for each team from CS2103 side. Maybe that's better than putting RS-specific files in AB as currently AB has no reason to depend on RS? However, we can expect RS to be developed into a more general tool (like gradle or asciidoc) at which point we can integrate it into AB the way we use gradle. At such a point we can have RS-specific files in AB without any misgivings.
